import React, {useState, useEffect} from 'react'
import Head from 'next/head'
import {HeadComponent, Characters, Paginated} from "../components"
import Link from "next/link"


export async function getServerSideProps () {
  // Con el Fetch conecto a la api
  const res = await fetch( `http://localhost:3000/api/characters` )
  const data = await res.json()

  //Paso data a la pagina por props
  return { props: { data } }
}



export default function Home({ data }) {


  const [character, setCharacter] = useState(data)

  const [pagina, setPagina] = useState(1);

  useEffect(() => {
   setCharacter(data)
  }, [data, setCharacter])

  console.log("character", character)
  
 const maximo = character.length / 10


 const filterCharacterPagina = () =>  character.slice( pagina , pagina + 10 ) //"corto" al estado data en 10. Así logro tener 10 character por pagina
    


  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main >

        <div className="bg-neutral-700 h-full w-full -z-20 flex flex-col">
          <HeadComponent />

          <h2 className=" my-7 font-sains text-4xl text-center text-zinc-200 underline decoration-soli">CHARACTERS</h2>
         
          <Paginated pagina={pagina} setPagina={setPagina} maximo={maximo} />

          <div className="h-full">

            {data.length > 0 &&

              filterCharacterPagina().map((c) => {

                const { url, name } = c;
                const id = url.slice(29); //Para obtener el id unico de cada character y luego utilizarlo en la ruta detail

                return (
                  <Link href={`/detail/${id}`} key={id} className="w-full flex justify-center">
                    <Characters id={id} name={name} />
                  </Link>
                )
              })}

          </div>
          </div>
      </main>

    </>
  )
}


