import React, {useState, useEffect} from 'react'
import Head from 'next/head'
import {HeadComponent, Characters, Paginated, Search} from "../components"
import Link from "next/link"


export async function getServerSideProps () {
  // Con el Fetch conecto a la api
  const res = await fetch( `http://localhost:3000/api/characters` )
  const data = await res.json()

  //Paso data a la pagina por props
  return { props: { data } }
}



export default function Home({ data }) {

  const [character, setCharacter] = useState(data)

  const [characterCopia, setCharacterCopia] = useState(data) //Copia de Character que la que muestro

  const [pagina, setPagina] = useState(0);  //Pagina actual

  const [maximo, setMaximo] = useState( Math.ceil(character.length / 10) - 1 )  //cantidad de paginas totales

  useEffect(() => {
   setCharacter(data)
   setCharacterCopia(data)
  }, [data, setCharacter])

  
 const itemsPorPagina = 10;
 const offset = pagina * itemsPorPagina;
 const limit = offset + itemsPorPagina;


 const filterCharacterPagina = () =>  characterCopia.slice( offset , limit  ) //"corto" al estado data en 10. Así logro tener 10 character por pagina
  

  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.png" />
      </Head>

      <main >
      <HeadComponent />

      <Search character={character} setCharacterCopia={setCharacterCopia} setMaximo={setMaximo}/>

        <div className="bg-black  h-full w-full flex flex-col justify-center items-center">

         <div className="border-2 border-zinc-900 shadow-xxl shadow-neutral-600/40 mt-16 h-full w-1/2 flex flex-col justify-center items-center">
         
         <h2 className=" my-7 font-sains text-4xl text-center text-zinc-200">CHARACTERS</h2>
         
          <Paginated pagina={pagina} setPagina={setPagina} maximo={maximo} />

      
     
            {characterCopia.length > 0 &&

              filterCharacterPagina().map((c) => {

                const { url, name } = c;
                const id = url.slice(29); //Para obtener el id unico de cada character y luego utilizarlo en la ruta detail

                return (
                  <Link href={`/detail/${id}`} key={id} className="w-1/4 flex justify-center">
                    <Characters name={name} />
                  </Link>
                )
              })
            
            }

            {
              filterCharacterPagina() === "" && (<p className=" my-7 font-sains text-4xl text-center text-zinc-200" >NO HAY NADA</p>)
            }

          </div>
          </div>
      </main>

    </>
  )
}


